.PHONY: generate

USAGE="build: build and install servers/client in go/bin
generate: generate go files from graphql and proto"

build:
	go build exo/...
	go build exo_client/...
	go build exo_server/...
	go install exo_client/...
	go install exo_server/...

generate:
	go generate exo_server/...

help:
	@echo "$(USAGE)"
